// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaksuooblyaogujnnxhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFha3N1b29ibHlhb2d1am5ueGhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTA3NzQsImV4cCI6MjA2MDU4Njc3NH0.eXY2l--7qVgTo9I5XKRizz5nt1K47-Omes_hXGR5O9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);