// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bktsoojafeirhykdcchl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrdHNvb2phZmVpcmh5a2RjY2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMjAxNjIsImV4cCI6MjA2MDU5NjE2Mn0.GvQE_JiRTOOuuxxmbtFAbchtvCALeknhGPaQWCXvNFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);